### ISSUE TITLE
Adding Nano

### ISSUE THREAD

**Issue by BitDesert** [DZGoldman/awdy#1]
**Name:** Nano
**Symbol:** NANO
**Client Codebase:** 1
**Consensus:** DPoS
**50 % Voting Power:**
https://mynano.ninja/api/accounts/active
Count votingweight until you reach 50% or the total supply of 133248289218203497353846153999000000001. You could count the Official Reps as one entitity.
**Peers:** https://api.nanocrawler.cc/peer_count
**Top Accounts:** https://api.nanocrawler.cc/accounts/1
**Incentivized:** No

**Comment by ghost** [comment]
I have added the following endpoint for the 50% voting power:
https://repnode.org/api/adjusted-nakamoto
Use the field "adjusted_nakamoto_online"

This number is basically computed based on the online representatives and the online voting power (see https://repnode.org/representatives/online) and then there are some representatives that are grouped together since they are controlled by the same entity (see https://repnode.org/representatives/groups).

(Edit: you can add a link to https://repnode.org/representatives/nakamoto)

**Comment by DZGoldman** [comment]
Thanks for the links guys! Looks like all we need is here — will update as soon as I get the chance.

**Comment by DZGoldman** [comment]
...I got the chance! It's live
